### ISSUE TITLE
[smartlyrics] Error in `lyrics` cmd

### ISSUE THREAD

**Issue by cool-aid-man** [kaogurai/cogs#16]
Hey Rayan, 

Getting this error from `<p>lyrics` command. 
Cog: `SmartLyrics`
```py
Traceback (most recent call last):
  File "/home/ubuntu/redenv/lib/python3.9/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/ubuntu/.local/share/Red-DiscordBot/data/dusky/cogs/CogManager/cogs/smartlyrics/smartlyrics.py", line 176, in lyrics
    spotify_id = self.get_user_status_song(ctx.author)
  File "/home/ubuntu/.local/share/Red-DiscordBot/data/dusky/cogs/CogManager/cogs/smartlyrics/smartlyrics.py", line 81, in get_user_status_song
    return s.track_id
AttributeError: 'str' object has no attribute 'track_id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/redenv/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/redenv/lib/python3.9/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/ubuntu/redenv/lib/python3.9/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'str' object has no attribute 'track_id'
```
Thanks

**Comment by Ryan5453** [comment]
Hi, sorry about that.

Can you confirm if SmartLyrics v2.1.4 fixes this issue?

**Comment by cool-aid-man** [comment]
Hii
Actually it triggered the `nonetype config` error, after updating yes
```py
Exception in command 'lyrics'
Traceback (most recent call last):
  File "/home/ubuntu/redenv/lib/python3.9/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/ubuntu/.local/share/Red-DiscordBot/data/dusky/cogs/CogManager/cogs/smartlyrics/smartlyrics.py", line 186, in lyrics
    lastfm_username = await lastfm_cog.config.user(ctx.author).lastfm_username()
AttributeError: 'NoneType' object has no attribute 'config'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/redenv/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/redenv/lib/python3.9/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/ubuntu/redenv/lib/python3.9/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'config'

```

**Comment by Ryan5453** [comment]
God I did a horrible job testing this cog, try v2.1.5

**Comment by cool-aid-man** [comment]
No worries
Always happy to help!

And **ye**s it did fix the issue. 

Thanks rayan 
Have a great night:)

**Comment by Ryan5453** [comment]
Perfect! Thanks, you too :)
