### ISSUE TITLE
[SmartLyrics] Command raised an exception: Exception: Could not get search results.

### ISSUE THREAD

**Issue by cool-aid-man** [kaogurai/cogs#32]
Hey Ryan,

Getting `Command raised an exception: Exception: Could not get search results.` from `ly`.
- The API is working - I can confirm that as I've tested it with `postman` by using my own **"Client Access Token"** and it's returning `200 ok`, so something else is acting weird.
- Here's the result:
![image](https://github.com/user-attachments/assets/ab0888c0-da5f-409f-9c10-a83066fe7bc2)
- Result from that test: https://gist.github.com/cool-aid-man/2e0b64db5db36c426469ac848662680d
----------
- Here's the full `traceback` from the errored command:
```py
Exception in command 'lyrics'
Traceback (most recent call last):
  File "/home/ubuntu/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/share/Red-DiscordBot/data/astra/cogs/CogManager/cogs/smartlyrics/smartlyrics.py", line 207, in lyrics
    results = await self._get_lyrics(spotify_track)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/share/Red-DiscordBot/data/astra/cogs/CogManager/cogs/smartlyrics/smartlyrics.py", line 91, in _get_lyrics
    track_id = await self._search(query)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/share/Red-DiscordBot/data/astra/cogs/CogManager/cogs/smartlyrics/smartlyrics.py", line 77, in _search
    raise Exception("Could not get search results.")
Exception: Could not get search results.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/redenv/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1366, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: Exception: Could not get search results.

```

Hope you get some time to look into it
Thanks

**Comment by Ryan5453** [comment]
What do you mean "Client Access Token"? The cog doesn't do any authentication.

Are you sure your IP didn't just get banned somehow? The cog still works for me

**Comment by cool-aid-man** [comment]
> What do you mean "Client Access Token"? The cog doesn't do any authentication.

Yes, the cog doesn't. I meant that since it's throwing me the error, I wanted to check if the API is working or not (for debugging purposes, basically)—hence, I used another service, [`Postman`](https://web.postman.co/), to check whether the API is up or down (and that service requires a Token, which you can generate via [Genius](https://genius.com/api-clients)).
Sorry, I could have been more clearer.

> Are you sure your IP didn't just get banned somehow? The cog still works for me

Oh god! How do I check it?
In our use case, the cog barely gets used **2-3 times a day**, sometimes even less or none. So unless it's related to that YouTube ban (where YouTube banned a large number of ASNs—the reason why audio is unusable/broken for many **many** users - including me), I don't see any viable reason why my IP could get banned from using the cog alone 😥! Unless, of course, I'm missing something else.

A bit more info (if it helps): Since the YouTube ban, I had unloaded the `Audio` cog but the `smartlyrics` cog was working fine until it stopped and started erroring a few days ago.

**Comment by cool-aid-man** [comment]
## Update
Ryan, looks like it is an IP ban.

Tried with this: 
```py
<p>eval
headers = {"X-Genius-iOS-Version": "6.7.0",
                "X-Genius-Logged-Out": "true",
                "User-Agent": "Genius/1015 CFNetwork/1390 Darwin/22.0.0",
}
async with aiohttp.ClientSession(headers=headers) as session:
    parms = {"q": "hello",}
    async with session.get('https://api.genius.com/search/multi', params=parms) as resp:
        print(resp.status)
        j = await resp.json()
        print(j)
```
And it returned `403` 👇
(Looks like the YouTube ban did effect the cog)
```py
403
Traceback (most recent call last):
  File "<eval command - snippet #8>", line 9, in func
    j = await resp.json()
        ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redenv/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1176, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.genius.com/search/multi?q=hello')

```
I suppose there's very little to do here but I still wanna ask - 
- Is there anything that could be done (like using an external lavalink node) to work around the ban, or could we appeal or use any other services for the cog as a fallback? 

(We actually love the cog so much and honestly, this is the **only** cog that has this ability to fetch the lyrics which is why asking this question, so if there's anything you could do would really be appreciated)

**Comment by sravan1946** [comment]
> ## Update
> Ryan, looks like it is an IP ban.
> 
> Tried with this:
> 
> ```python
> <p>eval
> headers = {"X-Genius-iOS-Version": "6.7.0",
>                 "X-Genius-Logged-Out": "true",
>                 "User-Agent": "Genius/1015 CFNetwork/1390 Darwin/22.0.0",
> }
> async with aiohttp.ClientSession(headers=headers) as session:
>     parms = {"q": "hello",}
>     async with session.get('https://api.genius.com/search/multi', params=parms) as resp:
>         print(resp.status)
>         j = await resp.json()
>         print(j)
> ```
> 
> And it returned `403` 👇 (Looks like the YouTube ban did effect the cog)

PS. this was the actuall responce we got back: https://gist.github.com/cool-aid-man/ab3f304871ece051914edaef80142fe3

**Comment by Ryan5453** [comment]
This doesn't have anything to do with a YouTube ban - it's just Cloudflare blocking your requests

**Comment by Ryan5453** [comment]
I just changed the headers used to contact Genius, let me know if it changes anything

**Comment by sravan1946** [comment]
Its still not able to fetch results

**Comment by Ryan5453** [comment]
This isn't really a thing that I can fix it seems - I'm not sure exactly how but Genius blocked you via Cloudflare. If you can get a new IP address it should fix it

**Comment by sravan1946** [comment]
we did some testing and making request using [curl_cffi](https://pypi.org/project/curl-cffi/) seems to work
![image](https://github.com/user-attachments/assets/7deead47-491b-4727-b5e2-b66e0293575c)

**Comment by Ryan5453** [comment]
Is this running on the same server though?

**Comment by cool-aid-man** [comment]
> Is this running on the same server though?

Yep, that's on the same server that is getting blocked otherwise without the lib

**Comment by mushwrooom** [comment]
Encountered an identical issue. Which was resolved by [curl_cffi](https://pypi.org/project/curl-cffi/). Just created an appropriate PR for the issue.
